# -*- mode: ruby -*-
# vi: set ft=ruby :
#
def local_cache(basebox_name)
  cache_dir = Vagrant::Environment.new.home_path.join('cache', 'apt', basebox_name)
  partial_dir = cache_dir.join('partial')
  FileUtils.mkdir_p(partial_dir) unless partial_dir.exist?
  cache_dir
end

Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-9.1"

  cache_dir = local_cache(config.vm.box)
  config.vm.synced_folder cache_dir, "/var/cache/apt/archives"

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 4
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get -qq update > /dev/null
    apt-get -qq install -y llvm clang gnat git vim > /dev/null

    # Get GHDL
    git clone https://github.com/tgingold/ghdl.git ghdl

    # Compile and install
    cd ghdl
    echo Configuring
    ./configure --prefix=/usr/local > configure.output
    echo Building
    make > make.output 2> make.stderr
    echo Installing
    make install > make_install.output

    # Test
    cd /home/vagrant
    cp -r /vagrant/hello_world .
    cd hello_world
    ghdl -a hello.vhdl
    ghdl -e hello_world
    ghdl -r hello_world
  SHELL
end
